# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cava Lab
subtitle: &subtitle Advancing interpretable and fair digital health
email: william.lacava@childrens.harvard.edu
# email: {% william.lacava@childrens.harvard.edu
description: *subtitle
domain: cavalab.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cavalab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: w_la_cava
github_username:  cavalab

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
show_excerpts: false # set to true to show excerpts on the homepage
# minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin:  "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise" "default" 
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  # - jekyll-katex
  - jekyll-include-cache
  - jekyll-target-blank

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-8CVW0XBQDT" # Replace this with your ID, or delete
    anonymize_ip         : true

# auto-generate id's for headings
markdown: kramdown
kramdown:
    auto_ids: true
    math_engine: mathjax

atom_feed:
  hide: true

include: ["_pages"]

# logo: "/assets/images/Cava_Lab_background.png"
# logo: "fas fa-microscope" 

author:
  # name: Cava Lab
  # bio: "Interpretable and fair machine learning for digital health"
  avatar: "/assets/images/space_bot3.jpg" 
  location: "Boston, MA"
  links: &links
    - label: "GitHub"
      icon: &gh "fab fa-fw fa-github"
      url: "https://github.com/cavalab"
    - label: "Twitter"
      icon: &twitter "fab fa-twitter"
      url: "https://twitter.com/w_la_cava"
    - label: "Email"
      icon: &email "fas fa-fw fa-envelope"
      url: "mailto:william.lacava@childrens.harvard.edu"
    - label: "Harvard Catalyst"
      icon: &catalyst "fas fa-project-diagram" 
      url: "https://connects.catalyst.harvard.edu/Profiles/display/Person/200560"
    - label: "CHIP"
      icon: &chip "fa fa-heartbeat"
      url: "http://chip.org"
    - label: "Boston Children's Hospital"
      icon: &bch "fa fa-medkit"
      url: "https://www.childrenshospital.org/"
    - label: "Harvard Medical School"
      icon: &hms "fa fa-university"
      url: "https://hms.harvard.edu/"

footer:
  links: *links

collections:
  members:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/
  publications:
    output: false
    permalink: /:collection/:path/

defaults:
  # everything
  - scope:
      path: ""
    values:
      # sidebar: true
      # nav: "main"
      layout: single
      toc: false
      author_profile: true
      show_date: false
      # classes: wide
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
