# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cava Lab
subtitle: Advancing interpretable and fair digital health
email: william.lacava@childrens.harvard.edu
# email: {% william.lacava@childrens.harvard.edu
description: >- # this means to ignore newlines until "baseurl:"
  Advancing interpretable and fair digital health
domain: cavalab.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cavalab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: w_la_cava
github_username:  cavalab

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
show_excerpts: true # set to true to show excerpts on the homepage
# minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin:   "default" #"contrast" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  # - jekyll-katex
  - jekyll-include-cache

google_analytics: UA-49830993-2          # Required - replace with your tracking id 

# auto-generate id's for headings
markdown: kramdown
kramdown:
    auto_ids: true

atom_feed:
  hide: true

include: ["_pages"]


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cavalab"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/w_la_cava"

author:
  # avatar: "assets/images/Cava_Lab_logo_bw.png"
  bio: "A research group run by William La Cava"
  links:
    - label: "CHIP"
      url: "http://chip.org"
    - label: "Boston Children's Hospital"
      url: "https://www.childrenshospital.org/"
    - label: "Harvard Medical School"
      url: "https://hms.harvard.edu/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cavalab"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/w_la_cava"

atom_feed:
  hide: true

collections:
  members:
    output: true
    permalink: /:collection/:path/

defaults:
  # _docs
  - scope:
      path: ""
    values:
      sidebar: false
        # nav: "main"
      layout: single
      toc: false
      author_profile: true
  - scope:
      path: ""
      type: members
    values:
      sidebar: false
        # nav: "main"
      layout: single
      toc: false
      author_profile: true
